FROM ghcr.io/lavalink-devs/lavalink:4-alpine

COPY application.yml /opt/Lavalink/application.yml

EXPOSE ${PORT:-2333}

ENTRYPOINT ["java", "-Djdk.tls.client.protocols=TLSv1.2", "-Xmx512M", "-jar", "Lavalink.jar"]
